# version: 1.0.0

add_newline = true

format = """$directory\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """$cmd_duration\
$git_branch\
$git_commit\
$git_metrics\
$docker_context\
$memory_usage\
$custom\
$status\
$os\
$battery\
$time"""

[fill]
symbol = ' '

[character]
format = " $symbol"
success_symbol = "[‚ùØ](bold italic bright-green)"
error_symbol = "[‚úó](italic red)"
vimcmd_symbol = "[‚ñ†](italic dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "‚óå"
vimcmd_replace_symbol = "‚ñ°"
vimcmd_visual_symbol = "‚ñº"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "‚ãà‚îà"
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "red bold italic"
format = "[$user]($style) "
disabled = false
show_always = false

[directory]
truncation_length = 2
use_os_path_sep = true
style = "bold ##62ADF4"
format = '[$path]($style)[$lock_symbol]($lock_style)'
read_only = "üîí"
read_only_style = "bold white"

[cmd_duration]
format = "[‚óÑ $duration ](italic white)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[‚ñ∂](blue italic)"

[localip]
ssh_only = true
format = " ‚óØ[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%a %d %b %Y %H:%M:%S"
utc_time_offset = "local"
style = "italic purple"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "‚ñà"
charging_symbol = "[‚Üë](italic bold green)"
discharging_symbol = "‚Üì"
unknown_symbol = "‚ñë"
empty_symbol = "‚ñÉ"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = "[‚ñ≥](bold italic bright-blue)"
style = "italic bright-blue"
truncation_symbol = "‚ãØ"
truncation_length = 11
ignore_branches = ["main", "master"]
only_attached = true

[git_metrics]
format = '([‚ñ¥$added]($added_style))([‚ñø$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[lua]
format = " [lua](italic) [${symbol}]($style)"
symbol = "Óò† "
style = "bold bright-yellow"

[python]
format = " [py](italic) [${symbol}]($style)"
symbol = "[‚åâ](bold bright-blue)‚åä "
style = "bold bright-yellow"

[package]
format = " [pkg](italic dimmed) [$symbol]($style)"
symbol = "Û∞èó "
style = "dimmed yellow italic bold"

[docker_context]
symbol = "Ôåà "
format = " docker [$symbol$context]($style)"

[golang]
symbol = "Óòß "
format = " go [$symbol]($style)"

[haskell]
symbol = "‚ùØŒª "
format = " hs [$symbol]($style)"

[java]
symbol = "‚à™ "
format = " java [${symbol}]($style)"

[memory_usage]
symbol = "Û∞çõ "
format = " mem [${ram}( ${swap})]($style)"

[hostname]
ssh_symbol = "Ó¨Å "
